### ISSUE TITLE
Stuck in a loop

### ISSUE THREAD

**Issue by Nyholm** [php-amqplib/php-amqplib#527]
I'm having this really weird issue which I think is related to this library. Admin may close this issue if it is not. 

Some of my requests or cli commands get stuck in a loop and eats up 100% of the CPU. When I do a `strace -p <PID>` I'll get the following. 

```
./bin/console rabbitmq:consumer -m 25 -r 'message' foo -l 256 --env=prod
```
```
mmap(NULL, 6291456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e07600000
munmap(0x7f8e07a01000, 2093056)         = 0
madvise(0x7f8e07600000, 4198400, MADV_HUGEPAGE) = 0
munmap(0x7f8e07000000, 4198400)         = 0
mmap(NULL, 4198400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e071ff000
munmap(0x7f8e071ff000, 4198400)         = 0
mmap(NULL, 6291456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e07000000
munmap(0x7f8e07401000, 2093056)         = 0
madvise(0x7f8e07000000, 4198400, MADV_HUGEPAGE) = 0
munmap(0x7f8e07600000, 4198400)         = 0
mmap(NULL, 4198400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e077ff000
munmap(0x7f8e077ff000, 4198400)         = 0
mmap(NULL, 6291456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e07600000
munmap(0x7f8e07a01000, 2093056)         = 0
madvise(0x7f8e07600000, 4198400, MADV_HUGEPAGE) = 0
munmap(0x7f8e07000000, 4198400)         = 0
mmap(NULL, 4198400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e071ff000
munmap(0x7f8e071ff000, 4198400)         = 0
mmap(NULL, 6291456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e07000000
munmap(0x7f8e07401000, 2093056)         = 0
madvise(0x7f8e07000000, 4198400, MADV_HUGEPAGE) = 0
munmap(0x7f8e07600000, 4198400)         = 0
mmap(NULL, 4198400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e077ff000
munmap(0x7f8e077ff000, 4198400)         = 0
mmap(NULL, 6291456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e07600000
```

As you can see, Im very much stuck :(

* [madvise](http://man7.org/linux/man-pages/man2/madvise.2.html) - give advice about use of memory
* [mmap, munmap](http://man7.org/linux/man-pages/man2/munmap.2.html) - map or unmap files or devices into memory

I do not see what can cause this. Here is my bundle config: 

```yaml
old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            keepalive: false
            heartbeat: 0
  consumers:
      foo:
          connection:       default
          exchange_options: { name: 'exchange', type: topic }
          queue_options:    { name: 'queue' }
          qos_options:      {prefetch_size: 0, prefetch_count: 50, global: false}
          callback:         'App\Consumer\StoreConsumer'
          idle_timeout:           5
          idle_timeout_exit_code: 0
          enable_logger: true
```
